# Gradle JVM
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

## Environment Properties
minecraft_version=1.20.1
minecraft_version_range=[1.20.1,1.21)
forge_version=47.4.4
forge_version_range=[47,)
loader_version_range=[47,)

mapping_channel=official
mapping_version=1.20.1

mod_id=project_babylon_weapons
mod_name=Project Babylon Weapons

mod_license=All Rights Reserved,GNU GPLv3

mod_version=1.5.0

mod_group_id=com.rave.projectbabylonweapons

mod_authors=White Rave

mod_description=Epic Fight addon with custom weapons and skills.



















































































