modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
logoFile="project_babylon_weapons_logo_big.png"
credits=""
authors="${mod_authors}"
description='''${mod_description}'''

[[dependencies.${mod_id}]]
modId="neoforge"
type="required"
versionRange="${neo_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="minecraft"
type="required"
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="epicfight"
type="required"
versionRange="[21.0.0,)"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="project_babylon_materials"
type="required"
versionRange="[1.1.3,)"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="irons_spellbooks"
type="required"
versionRange="[1.21.1,)"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="geckolib"
type="required"
versionRange="[4.7,)"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="acgbattlescytherevived"
type="optional"
versionRange="[1.0.0,)"
ordering="NONE"
side="BOTH"
